### ISSUE TITLE
Slideshow not working

### ISSUE THREAD

**Issue by echocage123** [CodyHouse/cd-testimonial-slideshow-changelog#1]
<img width="1440" alt="Снимок экрана 2022-05-23 в 17 15 17" src="https://user-images.githubusercontent.com/67440446/169839612-e5c400ec-d2ec-448e-a2a0-d83e81ed95a3.png">
Hello! Why its may not working

Included content:
```
    <link rel="stylesheet" href="https://unpkg.com/codyhouse-framework/main/assets/css/style.min.css">
    <link rel="stylesheet" href="css/1_custom-select.css">
    <link rel="stylesheet" href="css/1_drawer.css">
    <link rel="stylesheet" href="css/2_cart-drawer.css">
    <link rel="stylesheet" href="css/1_expandable-search.css">
    <link rel="stylesheet" href="css/2_slideshow.css">
    <link rel="stylesheet" href="css/3_testimonial-slideshow.css">

    <link rel="stylesheet" href="scss/_2_slideshow.scss">
    <link rel="stylesheet" href="scss/_3_testimonial-slideshow.scss">



    <script src="https://unpkg.com/codyhouse-framework/main/assets/js/util.js"></script>

    <script type="text/javascript" src="js/_1_custom-select.js"></script>
    <script type="text/javascript" src="js/_1_drawer.js"></script>
    <script type="text/javascript" src="js/_1_expandable-search.js"></script>
    <script type="text/javascript" src="js/_1_swipe-content.js"></script>
    <script type="text/javascript" src="js/_2_slideshow.js"></script>
```
Thanks in advance for your reply

**Comment by echocage123** [comment]
Nice support..

**Comment by claudia-romano** [comment]
Hi there, please use this tread only to provide info on your bug. If you need to contact us for different reasons, get in touch here:
https://codyhouse.co/contact

As for your issue, unfortunately I cannot debug it from a screenshot. It looks like the js of the component is missing. Did you check the console for error messages?

**Comment by claudia-romano** [comment]
Hi there, I'm closing this issue as no additional info was provided. Feel free to reopen it if you are still experiencing problems.
